services:
  - type: web
    name: rapid-saas-ai-store
    env: node
    plan: starter
    buildCommand: |
      npm install
      npx puppeteer browsers install chrome
      npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: rapid-saas-ai-store
          property: port
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
    autoDeploy: true
    branch: main
    rootDir: .
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: rapid-saas-ai-store-disk
      size: 1GB
      mountPath: /opt/render/project/src/uploads